// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides complete TypeScript interfaces for Mnemonica types

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

import type { ProtoFlat } from 'mnemonica';

export type Definitions = {
	createdAt: number;
	readonly size: number;
	get: (name: string) => Definitions_DefinitionEntry | undefined;
	has: (name: string) => boolean;
	set: (name: string, entry: Definitions_DefinitionEntry) => void;
	keys: () => MapIterator<string>;
	values: () => MapIterator<Definitions_DefinitionEntry>;
	clear: () => void;
	DefinitionEntry: new (data: { name: string; location: string; kind: string; parent: string | unknown; strictChain: boolean; blockErrors: boolean }) => Definitions_DefinitionEntry;
};

export type Definitions_DefinitionEntry = ProtoFlat<Definitions, {
	name: string;
	location: string;
	kind: string;
	parent: string | unknown;
	strictChain: boolean;
	blockErrors: boolean;
	DefinitionEntry: undefined;
}>;

export type Types = {
	createdAt: number;
	readonly size: number;
	get: (name: string) => Types_TypeEntry | undefined;
	has: (name: string) => boolean;
	set: (name: string, entry: Types_TypeEntry) => void;
	keys: () => MapIterator<string>;
	values: () => MapIterator<Types_TypeEntry>;
	clear: () => void;
	getLineForType: (typeName: string) => number | undefined;
	TypeEntry: new (data: { name: string; fullPath: string; parent?: string; properties: Map<string, string>; lineNumber: number }) => Types_TypeEntry;
};

export type Types_TypeEntry = ProtoFlat<Types, {
	name: string;
	fullPath: string;
	parent?: string;
	properties: Map<string, string>;
	lineNumber: number;
	TypeEntry: undefined;
}>;

export type Registry = {
	createdAt: number;
	makeProperty: (name: string, value: unknown) => void;
	readonly size: number;
	get: (name: string) => unknown | undefined;
	has: (name: string) => boolean;
	set: (name: string, entry: unknown) => void;
	keys: () => MapIterator<string>;
	values: () => MapIterator<unknown>;
	clear: () => void;
	loadFromWorkspace: (workspacePath: string) => Promise<void>;
	getDefinitions: () => Definitions | undefined;
	getTypes: () => Types | undefined;
	getUsages: () => Usages | undefined;
	getTrie: () => Trie | undefined;
	refresh: () => Promise<void>;
	DefinitionEntry: new (data: { id: string; name: string; filePath: string; line: number; column: number }) => Registry_DefinitionEntry;
};

export type Registry_DefinitionEntry = ProtoFlat<Registry, {
	id: string;
	name: string;
	filePath: string;
	line: number;
	column: number;
	DefinitionEntry: undefined;
}>;

export type LoggerTab = {
	createdAt: number;
	LogEntry: new (data: { level: 'info' | 'warning' | 'error'; message: string; timestamp: number; typeName?: string; error?: Error; args?: Array<unknown> }) => LoggerTab_LogEntry;
};

export type LoggerTab_LogEntry = ProtoFlat<LoggerTab, {
	level: 'info' | 'warning' | 'error';
	message: string;
	timestamp: number;
	typeName?: string;
	error?: Error;
	args?: Array<unknown>;
	LogEntry: undefined;
}>;

export type Main = {
	extensionVersion: string;
	createdAt: number;
	Adapter: new (data: { name: string; domain: string; enabled: boolean }) => Main_Adapter;
};

export type Main_Adapter = ProtoFlat<Main, {
	name: string;
	domain: string;
	enabled: boolean;
	createdAt: number;
	Adapter: undefined;
}>;

export type Scene2D = {
	createdAt: number;
	Camera2D: new (data: { x: number; y: number; zoom: number }) => Scene2D_Camera2D;
	GraphNode2D: new (data: { id: string; label: string; x: number; y: number; radius: number; color: string }) => Scene2D_GraphNode2D;
};

export type Scene2D_Camera2D = ProtoFlat<Scene2D, {
	x: number;
	y: number;
	zoom: number;
	Camera2D: undefined;
	GraphNode2D: undefined;
}>;

export type Scene2D_GraphNode2D = ProtoFlat<Scene2D, {
	id: string;
	label: string;
	x: number;
	y: number;
	radius: number;
	color: string;
	Link2D: new (data: { source: unknown; target: unknown; strength: number }) => Scene2D_GraphNode2D_Link2D;
	Tooltip2D: new (data: { targetNode: unknown; content: string; visible: boolean }) => Scene2D_GraphNode2D_Tooltip2D;
	GraphNode2D: undefined;
	Camera2D: undefined;
}>;

export type Scene2D_GraphNode2D_Link2D = ProtoFlat<Scene2D_GraphNode2D, {
	source: unknown;
	target: unknown;
	strength: number;
	Link2D: undefined;
	Tooltip2D: undefined;
}>;

export type Scene2D_GraphNode2D_Tooltip2D = ProtoFlat<Scene2D_GraphNode2D, {
	targetNode: unknown;
	content: string;
	visible: boolean;
	Tooltip2D: undefined;
	Link2D: undefined;
}>;

export type Scene3D = {
	createdAt: number;
	Camera3D: new (data: { x: number; y: number; z: number; zoom: number; rotationX: number; rotationY: number }) => Scene3D_Camera3D;
	GraphNode3D: new (data: { id: string; label: string; x: number; y: number; z: number; radius: number; color: string }) => Scene3D_GraphNode3D;
};

export type Scene3D_Camera3D = ProtoFlat<Scene3D, {
	x: number;
	y: number;
	z: number;
	zoom: number;
	rotationX: number;
	rotationY: number;
	Camera3D: undefined;
	GraphNode3D: undefined;
}>;

export type Scene3D_GraphNode3D = ProtoFlat<Scene3D, {
	id: string;
	label: string;
	x: number;
	y: number;
	z: number;
	radius: number;
	color: string;
	Link3D: new (data: { source: unknown; target: unknown; strength: number }) => Scene3D_GraphNode3D_Link3D;
	Tooltip3D: new (data: { targetNode: unknown; content: string; visible: boolean }) => Scene3D_GraphNode3D_Tooltip3D;
	GraphNode3D: undefined;
	Camera3D: undefined;
}>;

export type Scene3D_GraphNode3D_Link3D = ProtoFlat<Scene3D_GraphNode3D, {
	source: unknown;
	target: unknown;
	strength: number;
	Link3D: undefined;
	Tooltip3D: undefined;
}>;

export type Scene3D_GraphNode3D_Tooltip3D = ProtoFlat<Scene3D_GraphNode3D, {
	targetNode: unknown;
	content: string;
	visible: boolean;
	Tooltip3D: undefined;
	Link3D: undefined;
}>;

export type Trie = {
	createdAt: number;
	GraphNodeTrie: new (data: { id: string; name: string; path: string; depth: number; isLeaf: boolean }) => Trie_GraphNodeTrie;
};

export type Trie_GraphNodeTrie = ProtoFlat<Trie, {
	id: string;
	name: string;
	path: string;
	depth: number;
	isLeaf: boolean;
	LinkTrie: new (data: { parent: unknown; child: unknown; relation: 'subtype' | 'instance' }) => Trie_GraphNodeTrie_LinkTrie;
	ContextMenu: new (data: { targetNode: unknown; items: Array<object>; visible: boolean }) => Trie_GraphNodeTrie_ContextMenu;
	GraphNodeTrie: undefined;
}>;

export type Trie_GraphNodeTrie_LinkTrie = ProtoFlat<Trie_GraphNodeTrie, {
	parent: unknown;
	child: unknown;
	relation: 'subtype' | 'instance';
	LinkTrie: undefined;
	ContextMenu: undefined;
}>;

export type Trie_GraphNodeTrie_ContextMenu = ProtoFlat<Trie_GraphNodeTrie, {
	targetNode: unknown;
	items: Array<object>;
	visible: boolean;
	ContextMenu: undefined;
	LinkTrie: undefined;
}>;

export type Usages = {
	createdAt: number;
	readonly size: number;
	get: (name: string) => Array<Usages_UsageEntry>;
	has: (name: string) => boolean;
	set: (name: string, entry: Array<Usages_UsageEntry>) => void;
	keys: () => MapIterator<string>;
	values: () => MapIterator<Array<Usages_UsageEntry>>;
	clear: () => void;
	UsageEntry: new (usages: { typeName: string; kind: string; code: string; location: string }) => Usages_UsageEntry;
};

export type Usages_UsageEntry = ProtoFlat<Usages, {
	typeName: string;
	kind: string;
	code: string;
	location: string;
	UsageEntry: undefined;
}>;
