// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides complete TypeScript interfaces for Mnemonica types

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

// Helper type for nested type constructors
type TypeConstructor<T> = {
	new (...args: unknown[]): T;
	(...args: unknown[]): T;
};

export type DefinitionInstance = {
	id: string;
	name: string;
	fullPath: string;
	properties: unknown;
	Link: TypeConstructor<LinkInstance>;
}

export type LinkInstance = DefinitionInstance & {
	source: unknown;
	target: unknown;
	relation: unknown;
}

export type LoggerTabInstance = {
	createdAt: number;
	LogEntry: TypeConstructor<LogEntryInstance>;
}

export type LogEntryInstance = LoggerTabInstance & {
	level: unknown;
	message: string;
	timestamp: number;
	typeName: string;
	error: unknown;
	args: Array<unknown>;
}

export type MainInstance = {
	extensionVersion: string;
	createdAt: number;
	Adapter: TypeConstructor<AdapterInstance>;
}

export type AdapterInstance = MainInstance & {
	name: string;
	domain: string;
	enabled: boolean;
	createdAt: number;
}

export type RegistryInstance = {
	createdAt: number;
	DefinitionEntry: TypeConstructor<DefinitionEntryInstance>;
}

export type DefinitionEntryInstance = RegistryInstance & {
	id: string;
	name: string;
	filePath: string;
	line: number;
	column: number;
}

export type Scene2DInstance = {
	createdAt: number;
	Camera2D: TypeConstructor<Camera2DInstance>;
	GraphNode2D: TypeConstructor<GraphNode2DInstance>;
}

export type Camera2DInstance = Scene2DInstance & {
	x: number;
	y: number;
	zoom: number;
}

export type GraphNode2DInstance = Scene2DInstance & {
	id: string;
	label: string;
	x: number;
	y: number;
	radius: number;
	color: string;
	Link2D: TypeConstructor<Link2DInstance>;
	Tooltip2D: TypeConstructor<Tooltip2DInstance>;
}

export type Link2DInstance = GraphNode2DInstance & {
	source: unknown;
	target: unknown;
	strength: number;
}

export type Tooltip2DInstance = GraphNode2DInstance & {
	targetNode: unknown;
	content: string;
	visible: boolean;
}

export type Scene3DInstance = {
	createdAt: number;
	Camera3D: TypeConstructor<Camera3DInstance>;
	GraphNode3D: TypeConstructor<GraphNode3DInstance>;
}

export type Camera3DInstance = Scene3DInstance & {
	x: number;
	y: number;
	z: number;
	zoom: number;
	rotationX: number;
	rotationY: number;
}

export type GraphNode3DInstance = Scene3DInstance & {
	id: string;
	label: string;
	x: number;
	y: number;
	z: number;
	radius: number;
	color: string;
	Link3D: TypeConstructor<Link3DInstance>;
	Tooltip3D: TypeConstructor<Tooltip3DInstance>;
}

export type Link3DInstance = GraphNode3DInstance & {
	source: unknown;
	target: unknown;
	strength: number;
}

export type Tooltip3DInstance = GraphNode3DInstance & {
	targetNode: unknown;
	content: string;
	visible: boolean;
}

export type TrieInstance = {
	createdAt: number;
	GraphNodeTrie: TypeConstructor<GraphNodeTrieInstance>;
}

export type GraphNodeTrieInstance = TrieInstance & {
	id: string;
	name: string;
	path: string;
	depth: number;
	isLeaf: boolean;
	LinkTrie: TypeConstructor<LinkTrieInstance>;
	ContextMenu: TypeConstructor<ContextMenuInstance>;
}

export type LinkTrieInstance = GraphNodeTrieInstance & {
	parent: unknown;
	child: unknown;
	relation: unknown;
}

export type ContextMenuInstance = GraphNodeTrieInstance & {
	targetNode: unknown;
	items: unknown;
	visible: boolean;
}

export type TypesInstance = {
	createdAt: number;
	TypeEntry: TypeConstructor<TypeEntryInstance>;
}

export type TypeEntryInstance = TypesInstance & {
	id: string;
	name: string;
	fullPath: string;
	parent: string;
	properties: unknown;
}

export type UsagesInstance = {
	createdAt: number;
	UsageEntry: TypeConstructor<UsageEntryInstance>;
}

export type UsageEntryInstance = UsagesInstance & {
	id: string;
	typeName: string;
	filePath: string;
	line: number;
	column: number;
	context: string;
}
