// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides complete TypeScript interfaces for Mnemonica types

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

import type { ProtoFlat, TypeConstructor } from 'mnemonica';

export type Definition = {
	id: string;
	name: string;
	fullPath: string;
	properties: Map<string, object>;
	Link: TypeConstructor<Definition_Link>;
};

export type Definition_Link = ProtoFlat<Definition, {
	source: unknown;
	target: unknown;
	relation: 'extends' | 'implements' | 'contains';
	Link: undefined;
}>;

export type LoggerTab = {
	createdAt: number;
	LogEntry: TypeConstructor<LoggerTab_LogEntry>;
};

export type LoggerTab_LogEntry = ProtoFlat<LoggerTab, {
	level: 'info' | 'warning' | 'error';
	message: string;
	timestamp: number;
	typeName: string;
	error: Error;
	args: Array<unknown>;
	LogEntry: undefined;
}>;

export type Main = {
	extensionVersion: string;
	createdAt: number;
	Adapter: TypeConstructor<Main_Adapter>;
};

export type Main_Adapter = ProtoFlat<Main, {
	name: string;
	domain: string;
	enabled: boolean;
	createdAt: number;
	Adapter: undefined;
}>;

export type Registry = {
	createdAt: number;
	DefinitionEntry: TypeConstructor<Registry_DefinitionEntry>;
};

export type Registry_DefinitionEntry = ProtoFlat<Registry, {
	id: string;
	name: string;
	filePath: string;
	line: number;
	column: number;
	DefinitionEntry: undefined;
}>;

export type Scene2D = {
	createdAt: number;
	Camera2D: TypeConstructor<Scene2D_Camera2D>;
	GraphNode2D: TypeConstructor<Scene2D_GraphNode2D>;
};

export type Scene2D_Camera2D = ProtoFlat<Scene2D, {
	x: number;
	y: number;
	zoom: number;
	Camera2D: undefined;
	GraphNode2D: undefined;
}>;

export type Scene2D_GraphNode2D = ProtoFlat<Scene2D, {
	id: string;
	label: string;
	x: number;
	y: number;
	radius: number;
	color: string;
	Link2D: TypeConstructor<Scene2D_GraphNode2D_Link2D>;
	Tooltip2D: TypeConstructor<Scene2D_GraphNode2D_Tooltip2D>;
	GraphNode2D: undefined;
	Camera2D: undefined;
}>;

export type Scene2D_GraphNode2D_Link2D = ProtoFlat<Scene2D_GraphNode2D, {
	source: unknown;
	target: unknown;
	strength: number;
	Link2D: undefined;
	Tooltip2D: undefined;
}>;

export type Scene2D_GraphNode2D_Tooltip2D = ProtoFlat<Scene2D_GraphNode2D, {
	targetNode: unknown;
	content: string;
	visible: boolean;
	Tooltip2D: undefined;
	Link2D: undefined;
}>;

export type Scene3D = {
	createdAt: number;
	Camera3D: TypeConstructor<Scene3D_Camera3D>;
	GraphNode3D: TypeConstructor<Scene3D_GraphNode3D>;
};

export type Scene3D_Camera3D = ProtoFlat<Scene3D, {
	x: number;
	y: number;
	z: number;
	zoom: number;
	rotationX: number;
	rotationY: number;
	Camera3D: undefined;
	GraphNode3D: undefined;
}>;

export type Scene3D_GraphNode3D = ProtoFlat<Scene3D, {
	id: string;
	label: string;
	x: number;
	y: number;
	z: number;
	radius: number;
	color: string;
	Link3D: TypeConstructor<Scene3D_GraphNode3D_Link3D>;
	Tooltip3D: TypeConstructor<Scene3D_GraphNode3D_Tooltip3D>;
	GraphNode3D: undefined;
	Camera3D: undefined;
}>;

export type Scene3D_GraphNode3D_Link3D = ProtoFlat<Scene3D_GraphNode3D, {
	source: unknown;
	target: unknown;
	strength: number;
	Link3D: undefined;
	Tooltip3D: undefined;
}>;

export type Scene3D_GraphNode3D_Tooltip3D = ProtoFlat<Scene3D_GraphNode3D, {
	targetNode: unknown;
	content: string;
	visible: boolean;
	Tooltip3D: undefined;
	Link3D: undefined;
}>;

export type Trie = {
	createdAt: number;
	GraphNodeTrie: TypeConstructor<Trie_GraphNodeTrie>;
};

export type Trie_GraphNodeTrie = ProtoFlat<Trie, {
	id: string;
	name: string;
	path: string;
	depth: number;
	isLeaf: boolean;
	LinkTrie: TypeConstructor<Trie_GraphNodeTrie_LinkTrie>;
	ContextMenu: TypeConstructor<Trie_GraphNodeTrie_ContextMenu>;
	GraphNodeTrie: undefined;
}>;

export type Trie_GraphNodeTrie_LinkTrie = ProtoFlat<Trie_GraphNodeTrie, {
	parent: unknown;
	child: unknown;
	relation: 'subtype' | 'instance';
	LinkTrie: undefined;
	ContextMenu: undefined;
}>;

export type Trie_GraphNodeTrie_ContextMenu = ProtoFlat<Trie_GraphNodeTrie, {
	targetNode: unknown;
	items: Array<object>;
	visible: boolean;
	ContextMenu: undefined;
	LinkTrie: undefined;
}>;

export type Types = {
	createdAt: number;
	TypeEntry: TypeConstructor<Types_TypeEntry>;
};

export type Types_TypeEntry = ProtoFlat<Types, {
	id: string;
	name: string;
	fullPath: string;
	parent: string;
	properties: Map<string, string>;
	TypeEntry: undefined;
}>;

export type Usages = {
	createdAt: number;
	readonly size: number;
	get: (name: string) => Array<Usages_UsageEntry>;
	has: (name: string) => boolean;
	set: (name: string, entry: Array<Usages_UsageEntry>) => void;
	keys: () => MapIterator<string>;
	values: () => MapIterator<Array<Usages_UsageEntry>>;
	clear: () => void;
	UsageEntry: TypeConstructor<Usages_UsageEntry>;
};

export type Usages_UsageEntry = ProtoFlat<Usages, {
	typeName: string;
	kind: string;
	code: string;
	location: string;
	UsageEntry: undefined;
}>;
